version: '2'

services:
  webstack:
    build: ./
    environment:
      - TZ=Asia/Bangkok
      - DOCKER_API_VERSION=1.22
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - apache
  apache:
    image: httpd:2-alpine
    environment:
      - TERM=xterm-256color
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./data/vhosts:/data/vhosts
    volumes_from:
      - php
  dnsmasq:
    image: andyshinn/dnsmasq:2.75
    cap_add:
      - NET_ADMIN
  php:
    image: matthewhartstonge/stackme-php7-fpm:latest
    environment:
      - TERM=xterm-256color
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/logs:/data/logs
      - ./data/www:/data/www
      - ./etc/php/conf.d/:/usr/local/etc/php/conf.d
  mysql:
    image: mariadb:10
    volumes:
      - /var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TERM=xterm-256color
      - MYSQL_ROOT_PASSWORD=strongpasswordforroot
