# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 04:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('domain', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(b'^[a-z0-9\\-\\.]+\\.[a-z0-9]{1,4}$', b'Invalid domain, it should be something like domain.tld')])),
                ('path', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
